name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # we don't include 25.1 in the matrix due to an ert testing issue
          - 26.1
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - release-snapshot
    steps:
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Setup Cask
        uses: conao3/setup-cask@master

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test
        env:
          COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}
          COVERALLS_PARALLEL: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cask install
          cask exec ert-runner dired-rsync-ert.el

  finalize:
      runs-on: ubuntu-latest
      if: always()
      needs: test
      steps:
        - run: curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
