name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - release-snapshot
    steps:
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Cask
        run: git clone https://github.com/cask/cask ~/.cask

      - name: Add Cask to Path
        run: echo "$HOME/.cask/bin" >> $GITHUB_PATH

      - name: Validate Cask
        run: cask emacs --version

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Elisp Deps
        run: cask install
        
      - name: Build
        run: cask build

      - name: Run ERT tests
        run: cask exec ert-runner dired-rsync-ert.el
